### ISSUE TITLE
Add module to scrutinizer

### ISSUE THREAD

**Issue by chillu** [symbiote/silverstripe-multivaluefield#15]
Could you please add the module to scrutinizer? https://scrutinizer-ci.com/g/new. We're keeping track of all modules we use on our contributions dashboard (github-dashing.herokuapp.com), and I've added scrutinizer quality and coverage scores there. Doesn't require any config, just four clicks. You'll have to click "Schedule inspection" for the first run, after that it should kick off automatically on commits. You can also add badgets to your README.

If you feel like it, you could also add me as a collaborator :) There's a "Add collaborators to your repository" option on the homepage.

We're experimenting with a more fine tuned config, including code coverage running on travis, but that's not really to roll out yet (https://github.com/stojg/silverstripe-timeline). Happy to hear feedback and get help of course :)

**Comment by robbieaverill** [comment]
@nglasl do you think this is something that Symbiote could do?

**Comment by dhensby** [comment]
change here: https://scrutinizer-ci.com/g/silverstripe-australia/silverstripe-multivaluefield/settings#change_form_name_control_group

**Comment by maxime-rainville** [comment]
Just had a look and it's showing on the dashboard.

![image](https://user-images.githubusercontent.com/1168676/89379058-33ced980-d749-11ea-8b6e-4a30cad68ca1.png)
