### ISSUE TITLE
MultivalueField::isChanged always seems to return true if used with $form->loadDataFrom($obj);

### ISSUE THREAD

**Issue by micschk** [symbiote/silverstripe-multivaluefield#18]
I have an update email set to be sent when a user changes his/her details. The multivaluefield for phonenumbers is always (wrongly) reported to have changed.

Load member into form

``` php
...
$form->->loadDataFrom($member);
...
```

Then, when Member gets saved without any changed fields;

``` php
// this regular text/varchar returns false
$member->isChanged('FirstName');
// this multivaluefield (wrongly) returns true
$member->isChanged('PhoneNumbers');
```

**Comment by nyeholt** [comment]
Hmm, will look into the way things are being done, it may be a hangover from the 2.4 implementation that wasn't updated properly.

**Comment by silbinarywolf** [comment]
Just want to add that I utilize getChangedFields() to check if I actually need to do an expensive DB write. (Usually in migration tasks that need to be re-runnable).

So it'd be fantastic if in the SS4 migration, we fix this.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
