### ISSUE TITLE
Possibilty to set initial values?

### ISSUE THREAD

**Issue by brasileric** [symbiote/silverstripe-multivaluefield#35]
Hi,

Is it possible possible to set one or more initial values to the MultiValueTextField ? So that there are already some items set as suggestions for the user.
I tried already with setValue, but without luck.

**Comment by nyeholt** [comment]
You might be able to set the value of the field it is attached to instead? eg

```
$this->MultiField = array('one', 'two', 'three');

$field = MultiValueTextField::create('MultiField', 'My multifield);
```

**Comment by robbieaverill** [comment]
@brasileric feel free to reopen if you are having problems with this module, otherwise I'll assume it's been resolved since last year.
