### ISSUE TITLE
Strange behaviour on SS 3.4.1

### ISSUE THREAD

**Issue by digitall-it** [symbiote/silverstripe-multivaluefield#38]
I used MultiValueDropdownField like [this](http://www.sspaste.com/paste/show/58228223bb55f) but it doesn’t work perfectly, it happens [this]( https://dl.dropboxusercontent.com/u/9770206/enersolar-mvf.gif). Why?

**Comment by nyeholt** [comment]
I haven't actually tested it in 3.4.1, so it's likely a compatibility issue.

**Comment by digitall-it** [comment]
will try to produce a minimum use case on on a Page object in a fresh 3.4.1 installation and will report. However, no js console errors until now.

**Comment by robbieaverill** [comment]
How's you get on @digitall-it ?

**Comment by digitall-it** [comment]
Sorry, I forgot this thread, will test asap with latest 3.x.

**Comment by robbieaverill** [comment]
Closing as 3.4 is now unsupported. Feel free to reopen if you still experience this on 3.6 or newer
