### ISSUE TITLE
setValue() not chainable

### ISSUE THREAD

**Issue by wernerkrauss** [symbiote/silverstripe-multivaluefield#41]
As `MultivalueTextField::setValue()` doesn't return `$this` (as `FormField::setValue()` does) it's not chainable.

**Comment by SilbinaryWolf** [comment]
Why would you want that? It overrides the entire value.

**Comment by robbieaverill** [comment]
`FormField` in SS4 returns itself, so we just need to return the parent value instead of... not doing that:

```diff
-		parent::setValue($v);
+		return parent::setValue($v);
```

**Comment by robbieaverill** [comment]
Fixed with #49
