### ISSUE TITLE
Many many extrafields

### ISSUE THREAD

**Issue by sanderha** [symbiote/silverstripe-multivaluefield#43]
It seems none of the multivaliue fields can save a value properly to many many extra fields. I'm not sure whats happening, but it seems it doesnt create the saved array properly

**Comment by robbieaverill** [comment]
@sanderha do you have some example code to reproduce the problem?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
