### ISSUE TITLE
Database Value not unserialized / Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by Zauberfisch** [symbiote/silverstripe-multivaluefield#51]
As of 3.0.1 `->setValue(null, $record)` will no longer unserialize the database value taken from `$record[$this->name.'Value']` and thus an error will occur in `->forTemplate()` when trying to loop over a serialized string instead of an array.

Offending commit/change: https://github.com/symbiote/silverstripe-multivaluefield/commit/378c7fa70461cbb36cb5bba664695dbb28f4286d#diff-334ddfd75490b6cd46c0409657bbf5f9R65

**Comment by robbieaverill** [comment]
I see - perhaps we need to separate that last block of logic out again, e.g.:

```diff
- } elseif ($value && is_string($value)) {
-     $value = unserialize($value);
+ }
+ 
+ if ($value && is_string($value)) {
+     $value = unserialize($value);
```

What do you think @Zauberfisch? Would you be keen to make a pull request for this change?
