### ISSUE TITLE
MultiValueCheckboxField not working with an array map of options

### ISSUE THREAD

**Issue by michalkleiner** [symbiote/silverstripe-multivaluefield#61]
When options for MultiValueCheckboxField are not instances of DataObject, the $value wasn't populated correctly, failing to populate the ID and extra class.

#60 fixes this — targeted at 3.1 branch as SS4 version doesn't have this issue.

**Comment by robbieaverill** [comment]
Fixes in 3.1.x-dev with #60 - thanks @michalkleiner!

**Comment by michalkleiner** [comment]
Thanks for the merge @robbieaverill, could you please also tag 3.1.2? Ta.

**Comment by robbieaverill** [comment]
Done https://github.com/symbiote/silverstripe-multivaluefield/releases/tag/3.1.2
